export const messages = {
  LOGIN_SUCCESS: "Login successful",
  LOGIN_FAILED: "Login failed",
  FAILED_TO_STORE_OTP: "Failed to store OTP",
  OTP_SENT_SUCCESSFULLY: "OTP sent successfully",
  ACCOUNT_CREATED_AND_OTP_SENT:
    "Your account has been created. OTP sent to your email/number which is valid for 5 minutes!",
  VERIFICATION_REQUIRED_AND_OTP_SENT:
    "Verification required! OTP sent to your email/number which is valid for 5 minutes.",
  USER_NOT_FOUND: "User not found",
  USER_ALREADY_DELETED: "User is already deleted",
  USER_DELETED_SUCCESSFULLY: "User deleted successfully",
  INVALID_CREDENTIALS: "Invalid credentials",
  INVALID_OTP: "Incorrect/Expired OTP code",
  OTP_EXPIRED: "OTP expired, request a new one",
  OTP_VERIFIED: "OTP successfully verified",
  INTERNAL_SERVER_ERROR: "Internal server error",
  FAILED_TO_SEND_OTP: "Failed to send OTP",
  PASSWORD_ALREADY_EXISTS: "Password already exists",
  FAILED_TO_RESET_PASSWORD: "Failed to reset password",
  PASSWORD_RESET_SUCCESSFULLY: "Password reset successfully",
  INVALID_REFRESH_TOKEN: "Invalid refresh token",
  TOKEN_REFRESHED_SUCCESSFULLY: "Token refreshed successfully",
  LOGOUT_SUCCESS: "Logged out successfully",
  INVALID_ROLE: "Invalid role",
  INVALID_SOCIAL_AUTH_TYPE: "Invalid social auth type",
  INVALID_APPLE_TOKEN: "Invalid apple token",
  EMAIL_NOT_PROVIDED_BY_PROVIDER: "Email not provided by provider",
  GOOGLE_TOKEN_EXPIRED: "Google token expired",
  INVALID_GOOGLE_TOKEN: "Invalid google token",
  USER_AUTHENTICATED_SUCCESSFULLY: "User authenticated successfully",
  SOMETHING_WENT_WRONG: "Something went wrong",
  FILES_UPLOADED_SUCCESSFULLY: "Files uploaded successfully",
  FILE_DELETED_SUCCESSFULLY: "File deleted successfully",
  FAILED_TO_DELETE_FILE_FROM_CLOUD: "Failed to delete file from cloud",
  FAILED_TO_DELETE: "Failed to delete",
  USER_DELETED: "User deleted",
  INVALID_FILE: "Invalid or unsupported file format",
  FIREBASE_CREDENTIALS_MISSING:
    "Firebase credentials are not set in environment variables",
  FIREBASE_INITIALIZED: "Firebase Admin initialized",
  FIREBASE_SUBSCRIBE_ERROR: "Error subscribing to topic",
  FIREBASE_UNSUBSCRIBE_ERROR: "Error unsubscribing from topic",
  FIREBASE_SEND_ERROR: "Error sending to topic",
  FIREBASE_SUBSCRIBED_TO_TOPIC: "Subscribed tokens to topic",
  FIREBASE_UNSUBSCRIBED_FROM_TOPIC: "Unsubscribed tokens from topic",
  FIREBASE_NOTIFICATION_SENT_TO_TOPIC: "Notification sent to topic",
  INVALID_FIREBASE_TOKEN: "Invalid Firebase token",
  USER_BLOCKED: "Your account has been blocked by the Admin.",
  FILE_TOO_LARGE: "File size exceeds the 10MB limit",
};
